<div id="cookie-consent" class="cookie-consent p-4">
    <span>This site uses cookies to enhance user experience. see<a href="/policy" class="ml-1 text-decoration-none">Privacy policy</a> </span>
    <div class="mt-2 d-flex align-items-center justify-content-center g-2">
        <button onclick="allowCookies()" class="btn btn-sm btn-primary mx-1">Allow cookies</button>
        <button onclick="cancelCookies()" class="btn btn-sm btn-secondary">cancel</button>
    </div>
</div>