<div class="offcanvas offcanvas-start" tabindex="-1" id="phonelist" aria-labelledby="phonelistLabel">
    <div class="offcanvas-header">
        <a href="/" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
            <!-- Uncomment the line below if you also wish to use an image logo -->
            <!-- <img src="public/assets/img/logo.png" alt=""> -->
            <img src="<?= LOGO ?>" alt="<?= PROJECT_NAME ?>" class="img-fluid lazyload" width="50" loading="lazy">
            <h1>| <?= PROJECT_NAME ?><span>.</span></h1>
        </a>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <a class="nav-link scrollto" href="/about">About</a>
            </li>
            <li class="list-group-item">
                <a class="nav-link scrollto" href="/services">Services</a>
            </li>
            <li class="list-group-item">
                <a class="nav-link scrollto" href="/websites">websites</a>
            </li>
            <li class="list-group-item">
                <a class="nav-link scrollto" href="/products">projects</a>
            </li>
            <li class="list-group-item">
                <a class="nav-link scrollto" href="/blog">blog</a>
            </li>
            <li class="list-group-item">
                <a class="nav-link scrollto" href="/help">help</a>
            </li>
            <li class="list-group-item">
                <a class="nav-link scrollto" href="/policy">policy</a>
            </li>
            <li class="list-group-item">
                <a class="nav-link scrollto" href="/impression">impression</a>
            </li>
        </ul>

        <article class="my-5">
            <strong>Please note: This project is just a template to preview my experience. It is not a real project and I do not have any real-world examples yet.</strong>
        </article>

    </div>
</div>